[Icon Theme]
Name=AdaptiveFilesIcons
Comment=Adaptive Files scalable vector icon language
Inherits=Yaru,Adwaita,hicolor
Directories=scalable/apps,scalable/places,scalable/devices,scalable/mimetypes,scalable/actions

[scalable/apps]
Size=64
MinSize=16
MaxSize=512
Type=Scalable
Context=Applications

[scalable/places]
Size=64
MinSize=16
MaxSize=512
Type=Scalable
Context=Places

[scalable/devices]
Size=64
MinSize=16
MaxSize=512
Type=Scalable
Context=Devices

[scalable/mimetypes]
Size=64
MinSize=16
MaxSize=512
Type=Scalable
Context=MimeTypes

[scalable/actions]
Size=24
MinSize=12
MaxSize=128
Type=Scalable
Context=Actions
